[package]
name = "open_parcel_tracker_web"
version = "0.1.0"
edition = "2021"


[dependencies]
icu_locid = {version="1.5.0", features=["serde"]}
open_parcel_tracker = {path = "../open_parcel_tracker"}
rocket = {version="0.5.1", features=["json"]}
serde = "1.0.218"
strum = "0.27.1"
